config/routes.rb
Flix::Application.routes.draw do

  resources :championships
  resources :teams

  resources :teams do
    resources :players
  end

  root to: 'pages#home'

  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/faq', to: 'pages#faq'
  match '/prova', to: 'pages#prova'

  match '/signup', to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers # ex.: get /users/1/followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

end

app/models/championship.rb
class Championship < ActiveRecord::Base
  attr_accessible :description, :logo, :name, :team_id, :user_id, :teams_attributes
  has_many :teams
  belongs_to :user
  accepts_nested_attributes_for :teams, :reject_if => lambda { |a| a[:name].blank?}, :allow_destroy => true
  mount_uploader :logo,  ImageUploader
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  # GET /championships
  # GET /championships.json
  def index
    @championships = Championship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @championships }
    end
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
    @championship = Championship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @championship }
    end
  end

  # GET /championships/new
  # GET /championships/new.json
  def new


    @championship = Championship.new
    3.times do
      @championship.teams.build
    end



    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @championship }
    end
  end

  # GET /championships/1/edit
  def edit
    @championship = Championship.find(params[:id])
  end

  # POST /championships
  # POST /championships.json
  def create
    @championship = Championship.new(params[:championship])
    if @championship.user_id.nil?
      @championship.user_id=current_user.id
    end

    respond_to do |format|
      if @championship.save
        format.html { redirect_to @championship, notice: 'Championship was successfully created.' }
        format.json { render json: @championship, status: :created, location: @championship }
      else
        format.html { render action: "new" }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /championships/1
  # PUT /championships/1.json
  def update
    @championship = Championship.find(params[:id])

    respond_to do |format|
      if @championship.update_attributes(params[:championship])
        format.html { redirect_to @championship, notice: 'Championship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship = Championship.find(params[:id])
    @championship.destroy

    respond_to do |format|
      format.html { redirect_to championships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_form.html.erb
<%= javascript_include_tag "application"%>
<%= form_for(@championship) do |f| %>
  <% if @championship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@championship.errors.count, "error") %> prohibited this championship from being saved:</h2>

      <ul>
      <% @championship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.file_field :logo%><br />
  </div>
      <div class="put">
      <%= f.fields_for :teams do |builder| %>
          <%= render 'team_fields', :f => builder %>
          <p><%= link_to_add_fields "Add Answer", f , :teams %></p>
      <% end %>

      <div class="actions">
      </div>





<div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/championships/_team_fields.html.erb
<p class="players">
  <%= f.label :name, "Team" %><br />
  <%= f.text_field :name %>
  <%= link_to_function "Remove", "remove_players(this)" %>


</p>

app/views/championships/edit.html.erb
<h1>Editing championship</h1>

<%= render 'form' %>

<%= link_to 'Show', @championship %> |
<%= link_to 'Back', championships_path %>

app/views/championships/index.html.erb
<h1>Listing championships</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Logo</th>
    <th>Admin</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @championships.each do |championship| %>
  <tr>
    <td><%= championship.name %></td>
    <td><%= championship.description %></td>
    <td><%= championship.logo %></td>
    <td><%= link_to championship.user_id, user_path(championship.user_id) %></td>
    <td><%= championship.team_id %></td>
    <td><%= link_to 'Show', championship %></td>
    <td><%= link_to 'Edit', edit_championship_path(championship) %></td>
    <td><%= button_to 'Destroy', championship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Championship', new_championship_path %>

app/views/championships/new.html.erb
<h1>New championship</h1>

<%= render 'form' %>

<%= link_to 'Back', championships_path %>

app/views/championships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= image_tag @championship.logo  %>
</p>

<p>
  <b>Name:</b>
  <%= @championship.name %>
</p>

<p>
  <b>Description:</b>
  <%= @championship.description %>
</p>

<p>
  <b>Logo:</b>
  <%= @championship.logo %>
</p>

<p>
  <b>Admin:</b>
  <%= @championship.user_id %>
</p>

<p>
  <b>Team:</b>
  <%= @championship.team_id %>
</p>

<% for team in @championship.teams %>
    <b>Name:</b>
    <li><%= team.name %></li>

<% end %>



<%= link_to 'Edit', edit_championship_path(@championship) %> |
<%= link_to 'Back', championships_path %>