config/routes.rb
Flix::Application.routes.draw do

  resources :championships
  resources :teams

  resources :teams do
    resources :players
  end

  root to: 'pages#home'

  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/faq', to: 'pages#faq'
  match '/prova', to: 'pages#prova'

  match '/signup', to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers # ex.: get /users/1/followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://github.com/lam-2014/flix" alt="Flix on GitHub">Flix</a>
  </small>
  <nav role="navigation">
    <ul>
      <li><%=link_to "Faq", faq_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://bit.ly/lingambmult" alt="Linguaggi e Ambienti Multimediali">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "I AM CHAMPION", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links for toggling -->
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% #link_to is the Rails helper to create links (it generates <a.../> tags) %>
        <li><%=link_to "Home", root_path %></li>

        <% if signed_in? %>

            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Teams", teams_path %></li>
            <li><%= link_to "Championships", championships_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" id="accountMenu" data-toggle="dropdown">Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="accountMenu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
        <% else %>
            <li><%=link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div> <!--/.nav-collapse -->
  </div> <!-- /.container-fluid -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="http://htmlshim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= javascript_include_tag "application"%>
  <%= javascript_include_tag "autocomplete-rails.js" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <% # method to automatically prevent Cross-Site Request Forgery %>
  <%= csrf_meta_tags %>
  <% # partial for the HTML shim %>
  <%= render "layouts/shim" %>
</head>
<body>

<!-- Fixed navbar -->
<%= render "layouts/header" %>

<div class="container">
  <!-- Page content -->
  <% # the flash message; it supports different type of messages %>
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= value %>
      </div>
  <% end %>

  <%= yield %>

  <!-- Footer -->
  <%= render "layouts/footer" %>

  <% # show debug info if development is the active Rails env %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>

</html>